"""Initial schema

Revision ID: 31c2dfd4fb26
Revises: 
Create Date: 2026-05-26 20:13:59.660024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31c2dfd4fb26'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_templates',
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('subject_template', sa.Text(), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_index(op.f('ix_notification_templates_name'), 'notification_templates', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('notification_logs',
    sa.Column('log_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('template_id', sa.String(length=36), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['notification_templates.template_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_notification_logs_user_id'), 'notification_logs', ['user_id'], unique=False)
    op.create_table('reservations',
    sa.Column('reservation_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('specialist_id', sa.String(length=36), nullable=False),
    sa.Column('appointment_time', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialist_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reservation_id'),
    sa.UniqueConstraint('specialist_id', 'appointment_time', name='uq_specialist_appointment_time')
    )
    op.create_index(op.f('ix_reservations_patient_id'), 'reservations', ['patient_id'], unique=False)
    op.create_index(op.f('ix_reservations_specialist_id'), 'reservations', ['specialist_id'], unique=False)
    op.create_table('specialist_details',
    sa.Column('specialist_id', sa.String(length=36), nullable=False),
    sa.Column('specialization', sa.String(length=100), nullable=False),
    sa.Column('default_appointment_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('office_address', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['specialist_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('specialist_id')
    )
    op.create_table('specialist_schedule',
    sa.Column('block_id', sa.String(length=36), nullable=False),
    sa.Column('specialist_id', sa.String(length=36), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('block_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('end_time > start_time', name='chk_end_time_after_start_time'),
    sa.ForeignKeyConstraint(['specialist_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('block_id')
    )
    op.create_index(op.f('ix_specialist_schedule_specialist_id'), 'specialist_schedule', ['specialist_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_specialist_schedule_specialist_id'), table_name='specialist_schedule')
    op.drop_table('specialist_schedule')
    op.drop_table('specialist_details')
    op.drop_index(op.f('ix_reservations_specialist_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_patient_id'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_notification_logs_user_id'), table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_index(op.f('ix_notification_templates_name'), table_name='notification_templates')
    op.drop_table('notification_templates')
    # ### end Alembic commands ###
